version: '3.8'

services:
  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"  
    networks:
      - app-network

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"  
    networks:
      - app-network

  product-service:
    build:
      context: ./  
    container_name: product-service
    environment:
      DATABASE_URL: jdbc:mysql://product-db:3306/admin  # Corrected port
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - product-db
    networks:
      - app-network

  auth-service:
    build:
      context: ./authService  
    container_name: auth-service
    environment:
      DATABASE_URL: jdbc:mysql://auth-db:3306/admin  # Corrected port
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - auth-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
