version: '3.8'

services:
  auth-service:
    build:
      context: ./authService
    image: auth-service:latest
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-db:3306/auth_service_db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  product-service:
    build:
      context: ./
    image: product-service:latest
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-db:3306/product_service_db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: auth_service_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

