apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-external-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0a1ea60d512aec057