version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/admin
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - JWT_SECRET= my-secret-key
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"

